# Generated by Django 5.0.1 on 2024-01-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_footburger_footpasta_footpizza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DessertCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Десерт торт',
                'verbose_name_plural': 'Десерты торты',
            },
        ),
        migrations.CreateModel(
            name='DessertIceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Десерт: Snake',
                'verbose_name_plural': 'Десерты: Snake',
            },
        ),
        migrations.CreateModel(
            name='DessertSnake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Десерт: Snake',
                'verbose_name_plural': 'Десерты: Snake',
            },
        ),
        migrations.CreateModel(
            name='JuiceCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Напитки: Фруктовый сок',
                'verbose_name_plural': 'Напитки: Фруктовый сок',
            },
        ),
        migrations.CreateModel(
            name='JuiceFruitJuice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Напитки: Фруктовый сок',
                'verbose_name_plural': 'Напитки: Фруктовый сок',
            },
        ),
    ]
