# Generated by Django 5.0.1 on 2024-01-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_lowprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bread',
            options={'verbose_name': 'Хлеб(home)', 'verbose_name_plural': 'Хлеб(home)'},
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Торт(home)', 'verbose_name_plural': 'Торты(home)'},
        ),
        migrations.AlterModelOptions(
            name='donuts',
            options={'verbose_name': 'Пончик(home)', 'verbose_name_plural': 'Пончики(home)'},
        ),
        migrations.AlterModelOptions(
            name='lowprice',
            options={'verbose_name': 'Продукт с низким ценником(home)', 'verbose_name_plural': 'Продукты с низкими ценами(home)'},
        ),
    ]
