# Generated by Django 5.0.1 on 2024-01-10 13:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_bread_options_alter_cake_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='description1',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bread',
            name='description2',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bread',
            name='image1',
            field=models.ImageField(default=1, upload_to='LowPrice_image12', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bread',
            name='image2',
            field=models.ImageField(default=1, upload_to='LowPrice_image23', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bread',
            name='image3',
            field=models.ImageField(default=1, upload_to='LowPrice_image34', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bread',
            name='image4',
            field=models.ImageField(default=1, upload_to='LowPrice_image4', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='description1',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='description2',
            field=ckeditor.fields.RichTextField(default=11, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='image1',
            field=models.ImageField(default=1, upload_to='LowPrice_image111', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='image2',
            field=models.ImageField(default=11, upload_to='LowPrice_image222', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='image3',
            field=models.ImageField(default=1, upload_to='LowPrice_image333', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='image4',
            field=models.ImageField(default=11, upload_to='LowPrice_image444', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donuts',
            name='description1',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donuts',
            name='description2',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donuts',
            name='image1',
            field=models.ImageField(default=1, upload_to='LowPrice_image11', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donuts',
            name='image2',
            field=models.ImageField(default=1, upload_to='LowPrice_image22', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donuts',
            name='image3',
            field=models.ImageField(default=1, upload_to='LowPrice_image33', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donuts',
            name='image4',
            field=models.ImageField(default=1, upload_to='LowPrice_image44', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowprice',
            name='description1',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowprice',
            name='description2',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowprice',
            name='image1',
            field=models.ImageField(default=1, upload_to='LowPrice_image1', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowprice',
            name='image2',
            field=models.ImageField(default=11, upload_to='LowPrice_image2', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowprice',
            name='image3',
            field=models.ImageField(default=1, upload_to='LowPrice_image3', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowprice',
            name='image4',
            field=models.ImageField(default=1, upload_to='LowPrice_image4', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
