# Generated by Django 5.0.1 on 2024-01-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_bread_description1_bread_description2_bread_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='description1',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='description1',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='donuts',
            name='description1',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lowprice',
            name='description1',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
    ]
