# Generated by Django 5.0.1 on 2024-01-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Foot_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
            ],
            options={
                'verbose_name': 'Выпечка',
                'verbose_name_plural': 'Выпечки',
            },
        ),
    ]
