# Generated by Django 5.0.1 on 2024-01-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_foot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Advertising_image', verbose_name='Фотография')),
                ('logo', models.ImageField(upload_to='logo+image', verbose_name='Фотграфия для соц-сети')),
                ('url', models.URLField(verbose_name='URL - для insyagram')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
    ]
