# Generated by Django 5.0.1 on 2024-01-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_alter_blogpost_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Comments.image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('comments', models.TextField(verbose_name='Коментарии')),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
