# Generated by Django 5.0.1 on 2024-01-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_comments_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Коммент', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
