# Generated by Django 5.0.1 on 2024-01-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_alter_comments_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='email.com')),
                ('comment', models.TextField(verbose_name='Отправленный комментарии')),
            ],
        ),
    ]
