# Generated by Django 5.0.1 on 2024-01-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_sendcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendcomment',
            options={'verbose_name': 'Отправленный комментарии', 'verbose_name_plural': 'Отправленный комментарии'},
        ),
    ]
