# Generated by Django 5.0.1 on 2024-01-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Quality_image', verbose_name='Фотография')),
                ('info1', models.TextField(verbose_name='Информация')),
                ('info2', models.TextField(verbose_name='Информация')),
                ('info3', models.TextField(verbose_name='Информация')),
                ('info4', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Качество наших услуг',
                'verbose_name_plural': 'Качество наших услуг',
            },
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
