# Generated by Django 5.0.1 on 2024-01-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_foot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='BackImage_image1', verbose_name='Фотография для заднего фона')),
                ('image2', models.ImageField(upload_to='BackImage_image2', verbose_name='Фотография для заднего фона')),
                ('image3', models.ImageField(upload_to='BackImage_image3', verbose_name='Фотография для заднего фона')),
                ('image4', models.ImageField(upload_to='BackImage_image4', verbose_name='Фотография для заднего фона')),
                ('image5', models.ImageField(upload_to='BackImage_image5', verbose_name='Фотография для заднего фона')),
            ],
            options={
                'verbose_name': 'Фотография заднего фона',
                'verbose_name_plural': 'Фотографии заднего фона',
            },
        ),
        migrations.RemoveField(
            model_name='slide',
            name='back_image',
        ),
    ]
