# Generated by Django 5.0.1 on 2024-01-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_backimage_remove_slide_back_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backimage',
            name='image5',
        ),
    ]
