# Generated by Django 5.0.1 on 2024-01-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_cake_alter_bread_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='LowPrice_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена со скидкой')),
            ],
            options={
                'verbose_name': 'Продукт с низким ценником',
                'verbose_name_plural': 'Продукты с низкими ценами',
            },
        ),
    ]
