# Generated by Django 5.0.1 on 2024-01-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_lowprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='backimage',
            name='image5',
            field=models.ImageField(default=1, upload_to='BackImage_image5', verbose_name='Фотография для заднего фона'),
            preserve_default=False,
        ),
    ]
