# Generated by Django 5.0.1 on 2024-01-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo+image', verbose_name='Фотграфия для соц-сети'),
            preserve_default=False,
        ),
    ]
