# Generated by Django 5.0.1 on 2024-01-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_advertising_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Ass_logo', verbose_name='Логотип')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('url_instagram', models.URLField(verbose_name='URL - Instagram')),
                ('url_internet', models.URLField(verbose_name='URL - ...')),
                ('url_twitter', models.URLField(verbose_name='URL - Twitter')),
                ('url_you_tube', models.URLField(verbose_name='URL - You Tube')),
                ('adres', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='email.com')),
            ],
            options={
                'verbose_name': 'Основная настройка',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
        migrations.CreateModel(
            name='AssPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонные номера')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='base.ass')),
            ],
        ),
    ]
