# Generated by Django 5.0.1 on 2024-01-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_backimage_image6'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
