# Generated by Django 5.0.1 on 2024-01-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_delete_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quality',
        ),
    ]
