# Generated by Django 5.0.1 on 2024-01-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_delete_quality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foot',
        ),
    ]
