# Generated by Django 5.0.1 on 2024-01-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_delete_foot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bread',
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
        migrations.DeleteModel(
            name='Donuts',
        ),
    ]
