# Generated by Django 5.0.1 on 2024-01-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_delete_bread_delete_cake_delete_donuts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LowPrice',
        ),
    ]
