# Generated by Django 5.0.1 on 2024-01-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_delete_lowprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertising',
        ),
    ]
