# Generated by Django 5.0.1 on 2024-01-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_reservations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegrammBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='email.com')),
                ('subject', models.CharField(max_length=255, verbose_name='Услуга')),
                ('message', models.TextField(verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Обратная связь - Telegram',
                'verbose_name_plural': 'Обратная связь - Telegram',
            },
        ),
    ]
